name: Azure Function Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.x' 
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt 
        
    - name: Deploy to Azure Function
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Basecamp-Email-Forwarding-automation'
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
